"use client";
import React, { useState } from "react";
import { FaArrowUp, FaArrowDown } from "react-icons/fa";

const FAQPage = () => {
  const [expandedIndex, setExpandedIndex] = useState(null);

  const toggleAnswer = (index) => {
    setExpandedIndex(expandedIndex === index ? null : index);
  };

  const faqs = [
    {
      question: "Can I use the images generated by the platform for commercial purposes?",
      answer: `Commercial use of the images generated by our platform is exclusively available to our premium users. As a premium user, you are permitted to utilize the images for your commercial purposes without any restrictions. However, for our free users, while commercial use is not directly permitted, you can still enjoy generating images by giving credit to Imagine and mentioning our platform when using the images in any capacity. Upgrade to our premium plan for unrestricted commercial use and unlock the full potential of our image generation capabilities.`,
    },
    {
      question: "What payment options are available?",
      answer: `We offer a range of convenient payment options to ensure a seamless and hassle-free purchasing experience. The following methods are available: Link Payment: Our website allows you to make payments using a secure link provided during the checkout process. This method enables you to authorize the payment directly from your bank account, ensuring quick and efficient transactions. Credit Card: We accept all major credit cards, providing you with the flexibility to pay using your preferred card. Our payment gateway is encrypted and secure, safeguarding your personal and financial information. Debit Card: You can also make payments using your debit card. Simply enter your card details during the checkout process, and the payment will be processed securely. Please ensure that your debit card is enabled for online transactions. We prioritize the security of your payment information and adhere to industry best practices to protect your privacy. Our payment systems utilize encryption and comply with stringent security standards to safeguard your sensitive data. If you encounter any issues or have specific payment-related inquiries, our dedicated customer support team is available to assist you promptly at imagine.web.support@vyro.ai. We strive to provide a professional and reliable payment experience, ensuring your satisfaction throughout the purchasing process. Please note that the availability of specific payment options may vary depending on your location and the nature of the service being purchased. We recommend reviewing the checkout page for the most up-to-date information on available payment methods. Thank you for choosing our services. We look forward to serving you and providing a seamless payment experience.`,
    },
    {
      question: "Is there a free trial?",
      answer: `No, there is no free trial available for Imagine AI. However, users can still access and utilize a selection of non-premium features on the web platform. These features are designed to provide users with a glimpse into the capabilities and creative potential of Imagine AI. While the full range of premium features and advanced tools may require a subscription or purchase, the available non-premium features offer users an opportunity to explore the AI art generation process and experiment with basic artistic elements.`,
    },
    {
      question: "Can I cancel my Plan?",
      answer: `Yes, you can cancel your plan at any time. At Imagine AI, we understand that circumstances and preferences may change, and we want to provide flexibility to our users. We believe in offering a hassle-free experience, including the ability to cancel your subscription or plan whenever you need to. When you decide to cancel your plan, you can typically do so through your Manage subscriptions tab or by contacting our customer support team at imagine.web.support@vyro.ai. We strive to make the cancellation process straightforward and transparent, ensuring that you have full control over your subscription. It's important to note that cancellation terms may vary depending on the specific subscription or plan you have chosen. Some plans may have a minimum commitment period or cancellation fees associated with them. However, even with these considerations, we aim to keep the cancellation process as seamless as possible. We value our users and want to ensure their satisfaction with our services. While we would be sorry to see you go, we respect your decision and are committed to providing a positive experience throughout your subscription, as well as during the cancellation process. If you have any further questions or need assistance with canceling your plan, our customer support team is readily available to help guide you through the process and address any concerns you may have.`,
    },
    {
      question: "Can I upgrade or downgrade my current plan?",
      answer: `Yes, you have the flexibility to upgrade or downgrade your current plan at Imagine AI. We understand that your needs and requirements may evolve over time, and we want to accommodate those changes. If you find that your current plan no longer suits your needs and you require additional features or resources, you can upgrade your plan. You can do so by going to the manage subscriptions tab and choose the plan of your choice follow the steps along the way or you can contact our support team at imagine.web.support@vyro.ai. This typically involves accessing higher-tiered plans that offer expanded functionalities, increased limits, or additional benefits. The process to upgrade your plan is usually straightforward, and you can typically make the switch through your account settings or by reaching out to our customer support team. Similarly, if you find that you no longer require certain features or want to adjust your subscription to better align with your needs, you can downgrade your plan. Downgrading allows you to switch to a lower-tiered plan that still provides the core features you require, but at a reduced cost or with fewer resources. Like upgrading, the process to downgrade your plan can usually be done through your account settings or by contacting our customer support team. We strive to make the plan upgrade or downgrade process as seamless as possible, ensuring that you have the flexibility to adjust your subscription to meet your changing needs. Our customer support team is available to assist you throughout the process, answer any questions you may have, and guide you in making the right decision.`,
    },
    {
      question: "What is Imagine's refund policy?",
      answer: `At Vyro, we strive to provide the best possible experience for our customers. We understand that circumstances may arise where you may need to request a refund for your subscription. To view Imagine's detailed refund policy please direct to the following link: https://intercom.help/vyroai-pvt-ltd/en/articles/8153030-refund-policy`,
    },
  ];

  return (
    <div className="bg-black text-white flex">
      <div className="container flex flex-row mx-auto">
        <div className="w-1/2 p-8 flex flex-col justify-between">
          <div>
            <h1 className="text-6xl font-bold mb-8">Have questions? We have answers!</h1>
            <p className="mb-6">Want to know more? You can email us anytime at <a href="mailto:support@imagine.com" className="text-blue-400 underline">support@imagine.com</a></p>
            <a href="/launch-app" className="inline-block bg-violet-500 text-white px-6 py-3 rounded font-bold text-lg">
              Launch App
            </a>
          </div>
        </div>
        <div className="w-1/2 p-8">
          <h2 className="text-3xl font-bold mb-6">FAQ</h2>
          {faqs.map((faq, index) => (
            <div key={index} className="mb-4">
              <div 
                onClick={() => toggleAnswer(index)} 
                className="cursor-pointer flex items-center justify-between bg-gray-800 p-4 rounded mb-2"
              >
                <h3 className="text-xl font-bold">{faq.question}</h3>
                {expandedIndex === index ?  <FaArrowUp /> : <FaArrowDown /> }
              </div>
              {expandedIndex === index && (
                <div className="bg-gray-900 p-4 rounded text-lg">
                  {faq.answer}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default FAQPage;


